GET http://localhost:4004/catalog
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/$metadata
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/Sales
Authorization: Basic joe:
###
POST http://localhost:4004/catalog/Sales(1)
Authorization: Basic joe:
Content-Type: application/json

{}
###
GET http://localhost:4004/catalog/topSales(amount=700)
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/SalesOrders?$top=10&$filter=TotalNetAmount%20gt%202000&$orderby=SalesOrder%20desc
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/Sales(9)/CatalogService.largestOrder()
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/userInfo()
Authorization: Basic joe:
###
