general:
  inferBuildTool: true
  productiveBranch: 'main'

stages:
  'Confirm':
    manualConfirmation: false

  productionDeployment: # Modified Stage
    # cfTargets:  REMOVE THIS ENTIRE SECTION
    #   - appName: 'app'
    #     org: 'facd30cetrial'
    #     space: 'dev'
    #     apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
    #     credentialsId: 'deploy-to-cf'

steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

  cloudFoundryDeploy: # New Step for MTA Deployment
    mtaFilePath: 'mta.yaml'  # Path to your mta.yaml file (usually in the root)
    org: 'facd30cetrial'        # Your Cloud Foundry organization
    space: 'dev'              # Your Cloud Foundry space
    cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com' # Your CF API endpoint
    credentialsId: 'deploy-to-cf' # ID of your Cloud Foundry credentials in Jenkins
    deployType: 'mta'
    
# transport management upload
#  tmsUpload:
#    nodeName: 'dev'
#    credentialsId: 'tms-sk'
#    customDescription: 'app dev'
