general:
  inferBuildTool: true
  productiveBranch: 'main'

# ... other config ...

stages:
  productionDeployment:
    # REMOVE cloudFoundryDeploy step completely

steps:
  mavenExecute:  # Your existing Maven build step
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:  # Your existing versioning step
    versioningType: cloud_noTag

  deployToCF: # New shell script step
    sh: |
      cf login -a ${CF_API_ENDPOINT} -o ${CF_ORG} -s ${CF_SPACE} -u ${CF_USERNAME} -p ${CF_PASSWORD}
      cf deploy mta.yaml --no-confirm # Or any other cf deploy options you need
      cf logout
# transport management upload
#  tmsUpload:
#    nodeName: 'dev'
#    credentialsId: 'tms-sk'
#    customDescription: 'app dev'
